# Generated by Django 4.0.2 on 2022-02-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_city_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
